# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.24.0"

default_platform :ios

platform :ios do
  # desc "Runs all the tests"
  # lane :test do
  #   scan
  # end

  desc "Submit a new Beta Build to Testflight"
  lane :beta do
    # Build
    gym(
      scheme: "CZCMobileAdsSample",
      workspace: "CZCMobileAdsSample.xcworkspace",
      configuration: "Release",
      clean: true,
      export_method: "development"
    )
    # Push to HockeyApp
    hockey(
      api_token: "57a722097396402785476ecf8b6ba7f1",
      ipa: "CZCMobileAdsSample.ipa",
      notify: "0"
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    sh "rm -rf ~/Documents/CZC/pingstart-ios-sdk/CZCMobileAdsSample.app.dSYM.zip"
    sh "rm -rf ~/Documents/CZC/pingstart-ios-sdk/CZCMobileAdsSample.ipa"
  	# rm -rf CZCMobileAdsSample.app.dSYM.zip
  	# rm -rf CZCMobileAdsSample.ipa
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
